const menuData = [
  {
    id: 1,
    type: "tapas",
    name: "French Oysters 6 pcs / 12 pcs",
    "name thai": "หอยนางรมสด ",
    "name chinese": "法國生蠔 6 件 / 12 件",
    "name russian": "Французская устрица 6 шт. / 12шт.",
    price: "420/800",
    photo: "",
    category: ""
  },
  {
    id: 2,
    type: "tapas",
    name: "Guacamole",
    "name thai": "กัวคาโมเล่",
    "name chinese": "鳄梨蘸酱",
    "name russian": "Авокадо",
    price: 250,
    photo: "",
    category: ""
  },
  {
    id: 3,
    type: "tapas",
    name: "Bruschetta",
    "name thai": "บลูสเช็ทต้า",
    "name chinese": "意式焗蕃茄蓉多士",
    "name russian": "Брушкетта (тосты со свежими помидорами и базиликом)",
    price: 200,
    photo: "",
    category: ""
  },
  {
    id: 4,
    type: "tapas",
    name: "Tuna with Anchovy",
    "name thai": "ทูน่าแอนโชววี่",
    "name chinese": "吞拿魚伴銀魚",
    "name russian": "Тунец и Анчовы",
    price: 220,
    photo: "",
    category: ""
  },
  {
    id: 5,
    type: "tapas",
    name: "Smoked Salmon & Dill ",
    "name thai": "สโมคซัลมอน&ดิว",
    "name chinese": "三文魚配蒔蘿",
    "name russian": "Копченый лосось и укроп",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 6,
    type: "tapas",
    name: "Mozzarella & Parma Ham Rolls",
    "name thai": "มอสซาเรลล่าพาม่าแฮมโรล",
    "name chinese": "巴瑪火腿伴莫扎里拉芝士",
    "name russian": "Моззарелла и пармская ветчина",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 7,
    type: "tapas",
    name: "Clams in White Wine",
    "name thai": "หอยอบไวน์าว",
    "name chinese": "蛤蜊白葡萄酒",
    "name russian": "Моллюски в белом вине",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 8,
    type: "tapas",
    name: "Fritto Misto",
    "name thai": "ฟริตโต้มีสโต้",
    "name chinese": "意式炸海鮮",
    "name russian": "Мороженые морепродукты",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 9,
    type: "tapas",
    name: "Gambas al Ajillo - Tomato",
    "name thai": "กัมบัส-มะเขือเทศ",
    "name chinese": "西班牙式蕃茄香蒜炒蝦仁",
    "name russian": "Креветки с острым соусом, чесноком и оливковым маслом",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 10,
    type: "tapas",
    name: "Crab Meat au Gratin",
    "name thai": "เนื้อปูอบชีส",
    "name chinese": "焗蟹肉",
    "name russian": "Мясо краба",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 11,
    type: "tapas",
    name: "Salmon Tartar",
    "name thai": "ซัลมอนตาต้า",
    "name chinese": "三文鱼塔塔",
    "name russian": "Тартар лосося",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 12,
    type: "tapas",
    name: "Vegetable Spring rolls",
    "name thai": "ปอเปี๊ยะผัก",
    "name chinese": "素 菜 春 卷",
    "name russian": "Овощные весенние рулоны",
    price: 220,
    photo: "",
    category: ""
  },
  {
    id: 13,
    type: "tapas",
    name: "Fresh Springrolls ",
    "name thai": "ปอเปี๊ยะสดใส่กุ้ง",
    "name chinese": "新鲜的春卷用虾",
    "name russian": "Свежие весенние рулетики с креветками",
    price: 240,
    photo: "",
    category: ""
  },
  {
    id: 14,
    type: "tapas",
    name: "Chicken Sate",
    "name thai": "สะเต๊ะไก่",
    "name chinese": "沙 爹 雞",
    "name russian": "Куриный шашлык",
    price: 240,
    photo: "",
    category: ""
  },
  {
    id: 15,
    type: "tapas",
    name: "Phuket Fish Cakes",
    "name thai": "ทอดมันปลา",
    "name chinese": "布 吉 島 魚 餅",
    "name russian": "рыбный пирог",
    price: 240,
    photo: "",
    category: ""
  },
  {
    id: 16,
    type: "tapas",
    name: "Honey Spare Ribs",
    "name thai": "ซี่โครงหมูอบน้ำผึ้ง",
    "name chinese": "蜜 糖 排 骨",
    "name russian": "Медные запасные ребра",
    price: 260,
    photo: "",
    category: ""
  },
  {
    id: 17,
    type: "tapas",
    name: "Nuea Dad Deaw-(Sun Dried Beef)",
    "name thai": "เนื้อแดดเดียว",
    "name chinese": "晒干的牛肉",
    "name russian": "Сушеная говядина",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 18,
    type: "tapas",
    name: "Banana Blossom Salad",
    "name thai": "ยำหัวปลี",
    "name chinese": "泰式香蕉花沙律",
    "name russian": "Банановый цветочный салат",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 19,
    type: "tapas",
    name: "Seared Scallops & Coconut Tomkha Sauce",
    "name thai": "หอยเชลล์ย่างซอสต้มข่า",
    "name chinese": "烤扇贝和椰子酱",
    "name russian": "Морской гребешок и кокосовый соус Том Ха",
    price: 420,
    photo: "",
    category: ""
  },
  {
    id: 20,
    type: "tapas",
    name: "Fish Ceviche ",
    "name thai": "ปลาเซวิซเช่",
    "name chinese": "腌制生鱼",
    "name russian": "маринованная сырая рыба",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 21,
    type: "salad",
    name: "Capresse Salad",
    "name thai": "คาเปรสเซ่สลัด",
    "name chinese": "番茄芝士沙拉",
    "name russian": "Салат Капресе (помидоры с сыром моцарелла)",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 22,
    type: "salad",
    name: "Ceasar Salad",
    "name thai": "ซีซาร์สลัด",
    "name chinese": "雞凱撒沙律",
    "name russian": "Салат Цезарь с креветками либо курицей",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 23,
    type: "salad",
    name: "Avocado Sardine Salad",
    "name thai": "อาโวคาโดซาร์ดีนสลัด",
    "name chinese": "鳄梨沙丁鱼沙拉",
    "name russian": "Салат из авокадо сардин",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 24,
    type: "salad",
    name: "Mango,Parma Ham & Mozzarella Salad",
    "name thai": "สลัดมะม่วง แฮม ชีส",
    "name chinese": "芒果,巴瑪火腿伴莫扎里拉芝士",
    "name russian": "Манго, салат из пармской ветчины и моцарелла",
    price: 290,
    photo: "",
    category: ""
  },
  {
    id: 25,
    type: "salad",
    name: "Smoked Salmon & Shrimp Salad",
    "name thai": "สลัดซัลมอลกับกุ้งย่าง",
    "name chinese": "烟熏三文鱼和虾沙拉",
    "name russian": "Салат из копченого салата и креветок",
    price: 350,
    photo: "",
    category: ""
  },
  {
    id: 26,
    type: "pasta",
    name: "Spaghetti Tomato Sauce",
    "name thai": "สปาเก็ตตี้โตเมโต้",
    "name chinese": "蕃茄意粉",
    "name russian": "Спагетти с помидорами",
    price: 300,
    photo: "",
    category: ""
  },
  {
    id: 27,
    type: "pasta",
    name: "Penne Carbonara",
    "name thai": "เพนเน่คาร์โบนาร่า",
    "name chinese": "意大利面和奶油芝士",
    "name russian": "Пенне Карбонара",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 28,
    type: "pasta",
    name: "Fettuccine Bolognese",
    "name thai": "เฟตตุชินี่โบโลเนส",
    "name chinese": "蕃茄免治牛肉闊麵條",
    "name russian": "Феттучини Болоньезе",
    price: 340,
    photo: "",
    category: ""
  },
  {
    id: 29,
    type: "pasta",
    name: "Fettuccini Shrimps & Mushrooms",
    "name thai": "เฟตตุชินี่กุ้งกับเห็ด",
    "name chinese": "蝦配蘑菇闊麵條",
    "name russian": "Креветки и грибы Феттучини",
    price: 360,
    photo: "",
    category: ""
  },
  {
    id: 30,
    type: "pasta",
    name: "Spaghetti Vongole ",
    "name thai": "สปาเก็็ตตี้หอยไวน์ขาว",
    "name chinese": "白酒燴蜆意粉",
    "name russian": "Спагетти с моллюсками и соусом",
    price: 360,
    photo: "",
    category: ""
  },
  {
    id: 31,
    type: "pasta",
    name: "Spaghetti Pesto & Scallops",
    "name thai": "สปาเก็ตตี้ี้เพสโต้หอยเชลล์",
    "name chinese": "意大利面香蒜酱和扇贝",
    "name russian": "Спагетти Песто и гребешок",
    price: 480,
    photo: "",
    category: ""
  },
  {
    id: 32,
    type: "pasta",
    name: "Linguini Tuna & Capers",
    "name thai": "ลิงกิวนี่ทูน่าเคเปอร์",
    "name chinese": "扁面金枪鱼",
    "name russian": "Лингвиновый тунец",
    price: 360,
    photo: "",
    category: ""
  },
  {
    id: 33,
    type: "pasta",
    name: "Linquini Lobster (for 2)",
    "name thai": "ลิิงกิวนี่ล้อปเตอร์ สำหรับ2 คน",
    "name chinese": "扁面条和龙虾 (2人)",
    "name russian": "Омар спагетти (на 2 персоны)",
    price: 2100,
    photo: "",
    category: ""
  },
  {
    id: 34,
    type: "pasta",
    name: "Risotto with Mushrooms",
    "name thai": "รีซอสโต้เห็ด",
    "name chinese": "蘑菇意式飯",
    "name russian": "Белыми грибами Ризотто",
    price: 360,
    photo: "",
    category: ""
  },
  {
    id: 35,
    type: "pasta",
    name: "Risotto Saffron with Shrimps and Scallops",
    "name thai": "รีซอสโต้กุ้งและหอยเชลล์",
    "name chinese": "意大利烩饭藏红花与虾和扇贝",
    "name russian": "Rizotto Shafran s krevetkami i grebeshkami",
    price: 550,
    photo: "",
    category: ""
  },
  {
    id: 36,
    type: "main course",
    name: "Chicken Milanese & French Fries",
    "name thai": "ไก่ชุบแป้งขนมปังกับเฟร้นฟรายส์",
    "name chinese": "意式炸雞伴薯條",
    "name russian": "Ципленок по Милански",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 37,
    type: "main course",
    name: "Grilled Duck Breast with Mango Tartar",
    "name thai": "อกเป็ดย่างกับสลัดมะม่วง",
    "name chinese": "烤鴨配芒果醬汁",
    "name russian": "Жареная утиная грудка с салатом манго",
    price: 360,
    photo: "",
    category: ""
  },
  {
    id: 38,
    type: "main course",
    name: "Chargrilled Salmon with Asparagus ",
    "name thai": "ซัลมอลย่างกับหน่อไม้ฝรั่ง",
    "name chinese": "烤三文鱼配芦笋",
    "name russian": "Лосось на гриле со спаржей",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 39,
    type: "main course",
    name: "Grilled Seabass Steak with Dill Sauce",
    "name thai": "ปลาซีบาสย่างกับซอสดิว",
    "name chinese": "烤鲈鱼排配莳萝酱",
    "name russian": "Морской окунь с укропным соусом",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 40,
    type: "main course",
    name: "Grilled Australian Beef Tenderloin",
    "name thai": "เนื้อสันในย่าง",
    "name chinese": "烤澳大利亚牛里脊肉",
    "name russian": "Говяжье филе с винным соусом",
    price: 850,
    photo: "",
    category: ""
  },
  {
    id: 41,
    type: "main course",
    name: "Surf anf Turf",
    "name thai": "เซริฟแอนด์เทริฟ",
    "name chinese": "烤牛肉和海鲜",
    "name russian": "Блюдо из мясных изделий и морепродуктов",
    price: 1600,
    photo: "",
    category: ""
  },
  {
    id: 42,
    type: "seafood",
    name: "Garlic Squid",
    "name thai": "ปลาหมึกทอดกระเทียม",
    "name chinese": "蒜香魷魚",
    "name russian": "Чеснок-кальмар",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 43,
    type: "seafood",
    name: "Stir Fried Squid with Basil",
    "name thai": "ปลาหมึึกผัดใบโหระพา",
    "name chinese": "羅勒炒魷魚",
    "name russian": "Перемешать жареный кальмары с базиликом",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 44,
    type: "seafood",
    name: "Garlic Shrimps",
    "name thai": "กุ้งทอดกระเทียม",
    "name chinese": "蒜香蝦",
    "name russian": "Чесночные креветки",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 45,
    type: "seafood",
    name: "Clams & Sweet Chili Sauce",
    "name thai": "หอยผัดน้ำพริกเผา",
    "name chinese": "甜辣酱炒蜆",
    "name russian": "Моллюски и сладкий соус чили",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 46,
    type: "seafood",
    name: "Fish in Tamarind Sauce",
    "name thai": "ปลาซอสมะขาม",
    "name chinese": "酸甜炸魚",
    "name russian": "Рыба в соусе Тамаринд",
    price: 380,
    photo: "",
    category: ""
  },
  {
    id: 47,
    type: "seafood",
    name: "Fish - Sea Bass ( whole )",
    "name thai": "ปลากระพงขาว (ตัว)",
    "name chinese": "鱼 - 鲈鱼（整体）",
    "name russian": "Рыба - морской окунь (цельный)",
    price: 480,
    photo: "",
    category: ""
  },
  {
    id: 48,
    type: "seafood",
    name: "Tiger Prawns",
    "name thai": "กุุ้งลายเสือ",
    "name chinese": "老虎蝦",
    "name russian": "тигровые креветки",
    price: "320/100g",
    photo: "",
    category: ""
  },
  {
    id: 49,
    type: "seafood",
    name: "Phuket Lobster",
    "name thai": "กุ้งล็อปสเตอร์",
    "name chinese": "普吉岛龙虾",
    "name russian": "Пхукет Лобстер",
    price: "350/100g",
    photo: "",
    category: ""
  },
  {
    id: 50,
    type: "seafood",
    name: "BBQ'd Free Range Chicken & Papaya salad",
    "name thai": "ไก่ย่างส้มตำ",
    "name chinese": "烤自由放养的鸡",
    "name russian": "Цыпленок, приготовленный на гриле",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 51,
    type: "thai dish",
    name: "Chicken with Cashew Nut",
    "name thai": "ไก่่ผัดเม็ดมะม่วง",
    "name chinese": "腰果雞丁",
    "name russian": "Курица с орехом кешью",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 52,
    type: "thai dish",
    name: "Chicken with Holy Basil & Chilli",
    "name thai": "ไก่ผัดกระเพรา",
    "name chinese": "与圣洁蓬蒿和辣椒的鸡肉",
    "name russian": "Курица со святыми листьями базилика и чили",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 53,
    type: "thai dish",
    name: "Chicken Green Curry",
    "name thai": "แกงเขียวหวานไก่",
    "name chinese": "鸡肉绿咖喱",
    "name russian": "Куриный зеленый карри",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 54,
    type: "thai dish",
    name: "Garlic Beef",
    "name thai": "เนื้อกระเทียมพริกไทย",
    "name chinese": "蒜香牛肉",
    "name russian": "чесночная говядина",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 55,
    type: "thai dish",
    name: "Beef Green Curry",
    "name thai": "แกวเขียวหวานเนื้อ",
    "name chinese": "牛肉绿咖喱",
    "name russian": "Говядина зеленое карри",
    price: 320,
    photo: "",
    category: ""
  },
  {
    id: 56,
    type: "thai dish",
    name: "Stir Fried Morning Glory",
    "name thai": "ผักบุ้งไฟแดง",
    "name chinese": "炒通菜",
    "name russian": "Жареные овощи",
    price: 200,
    photo: "",
    category: ""
  },
  {
    id: 57,
    type: "thai dish",
    name: "Stir Fried Bargu Leaves with Eggs",
    "name thai": "ผักเหมียงผัดไข่",
    "name chinese": "炒蔬菜和鸡蛋",
    "name russian": "Жареные овощи и яйца",
    price: 200,
    photo: "",
    category: ""
  },
  {
    id: 58,
    type: "thai dish",
    name: "Stir Fried Chinese Kale & Shiitake Mushrooms",
    "name thai": "คะน้าเห็ดหอม",
    "name chinese": "炒中国羽衣甘蓝和香菇",
    "name russian": "Жареные китайские кели и грибы",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 59,
    type: "Soup , Noodle & Rice",
    name: "Tom Yam Kung",
    "name thai": "ต้มยำกุ้ง",
    "name chinese": "酸辣蝦湯",
    "name russian": "Том Ям Кунг",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 60,
    type: "Soup , Noodle & Rice",
    name: "Tom Ka Gai",
    "name thai": "ต้มข่าไก่",
    "name chinese": "酸辣椰奶雞湯",
    "name russian": "Том Кха Цыпленок",
    price: 220,
    photo: "",
    category: ""
  },
  {
    id: 61,
    type: "Soup , Noodle & Rice",
    name: "Chicken Noodle Soup",
    "name thai": "ก๋วยเตี๋ยวน้ำไก่",
    "name chinese": "雞湯麵",
    "name russian": "Суп из куриного лапши",
    price: 180,
    photo: "",
    category: ""
  },
  {
    id: 62,
    type: "Soup , Noodle & Rice",
    name: "Pad Thai Noodles with Shrimps",
    "name thai": "ผัดไทยกุ้งสด",
    "name chinese": "泰式炒麵",
    "name russian": "Пэд Тайская лапша с креветками",
    price: 240,
    photo: "",
    category: ""
  },
  {
    id: 63,
    type: "Soup , Noodle & Rice",
    name: "Pineapple Fried Rice",
    "name thai": "ข้าวผัดสัปรด",
    "name chinese": "菠蘿炒飯",
    "name russian": "Ананас Жареный рис",
    price: 240,
    photo: "",
    category: ""
  },
  {
    id: 64,
    type: "Soup , Noodle & Rice",
    name: "Nasi Goreng (Indonesian Fried Rice)",
    "name thai": "นาซิโกเร็ง",
    "name chinese": "炒饭",
    "name russian": "Наси Горенг",
    price: 230,
    photo: "",
    category: ""
  },
  {
    id: 65,
    type: "Soup , Noodle & Rice",
    name: "Crab Meat Fried Rice",
    "name thai": "ข้าวผัดปู",
    "name chinese": "蟹肉炒饭",
    "name russian": "Краб-мясо Жареный рис",
    price: 230,
    photo: "",
    category: ""
  },
  {
    id: 66,
    type: "Soup , Noodle & Rice",
    name: "Chicken Fried Rice",
    "name thai": "ข้าวผัดไก่",
    "name chinese": "雞炒飯",
    "name russian": "Куриный жареный рис",
    price: 180,
    photo: "",
    category: ""
  },
  {
    id: 67,
    type: "Soup , Noodle & Rice",
    name: "Kao Soi : Chiang Mai Noodles ( only Fri,Sat & Sun)",
    "name thai": "ข้าวซอยไก่",
    "name chinese": "咖喱湯麵",
    "name russian": "Яйцо-лапша в курином карри",
    price: 180,
    photo: "",
    category: ""
  },
  {
    id: 68,
    type: "all day breakfast",
    name: "2 Eggs with Sausage and Bacon(any style)",
    "name thai": "ไข่ชุดอาหารเช้า",
    "name chinese": "香腸煙肉蛋(2隻)",
    "name russian": "2 яйца с колбасой и беконом",
    price: 280,
    photo: "",
    category: ""
  },
  {
    id: 69,
    type: "all day breakfast",
    name: "Blueberry Pancakes",
    "name thai": "แพนเค็กบลูเบอรี่",
    "name chinese": "藍 莓 班 戟",
    "name russian": "Черничный блин",
    price: 150,
    photo: "",
    category: ""
  },
  {
    id: 70,
    type: "all day breakfast",
    name: "Banana Pancakes",
    "name thai": "แพนเค็กกล้วย",
    "name chinese": "香 蕉 班 戟",
    "name russian": "Банановый блин",
    price: 150,
    photo: "",
    category: ""
  },
  {
    id: 71,
    type: "all day breakfast",
    name: "Stir Fried Egg Noodles & Chicken",
    "name thai": "ผัดหมี่เหลืองใส่ไก่",
    "name chinese": "炒蛋麵和鸡肉",
    "name russian": "Жареная яичная лапша и курица",
    price: 200,
    photo: "",
    category: ""
  },
  {
    id: 72,
    type: "all day breakfast",
    name: "Shrimp Boiled Rice",
    "name thai": "ข้าวต้มกุ้ง",
    "name chinese": "蒸 蝦 飯",
    "name russian": "Кремовый отварной рис",
    price: 240,
    photo: "",
    category: ""
  }
];

export default menuData;
